### ISSUE TITLE
Can you share the following source file? I would like to modify some options myself.

### ISSUE THREAD

**Issue by kiong2016** [mechano/Kingroon_KP3S_Pro_Marlin_Firmware#7]
Can you share the following source file? I would like to modify some options myself.

**Comment by mechano** [comment]
If you download the archive you'll find inside the .bin, Configuration.h Configuration_adv.h. 
The other files you download from official Marlin project.

**Comment by kiong2016** [comment]
Oh, yes, thank you.

**Comment by kiong2016** [comment]
I have a few more questions. The motherboard model of my KP3S Pro is Kingroon KP3 v1.3, and the chip model is GD32F303. In the Configuration.h file, at line 94, it says "#define MOTHERBOARD BOARD_MKS_ROBIN_NANO." Should I choose BOARD_MKS_ROBIN_NANO or BOARD_MKS_ROBIN_NANO_V2? I am using VSCode and PlatformIO for compilation. What should I fill in for the line "default_envs = mega2560" in the platformio.ini file?

**Comment by mechano** [comment]
Leave the BOARD_MKS_ROBIN_NANO

**Comment by kiong2016** [comment]
Sure, I'll give it a try. Thank you very much for your assistance.

**Comment by mechano** [comment]
Let me know if it works for you.

**Comment by kiong2016** [comment]
![屏幕截图 2023-11-02 201747](https://github.com/mechano/Kingroon_KP3S_Pro_Marlin_Firmware/assets/17523804/719847ef-7062-4668-883a-60825f010a7b)
The motherboard model of my KP3S Pro is Kingroon KP3 v1.3, and the chip model is GD32F303.  Which one should I choose

**Comment by kiong2016** [comment]
I tried replacing the file for compilation, but it resulted in an error. I'm unable to resolve this issue. My requirement is simple: I want to set the language displayed on the LCD to Chinese. It would be great if you could help me compile a firmware version with BLTouch in Chinese. If you don't have the time, it's okay. I'll try using the English version.

**Comment by mechano** [comment]
Which error?
And sorry I don't know chinese, I can't try the firmware if I use that language.

**Comment by kiong2016** [comment]
You're welcome! I'm glad I could assist you. Thank you for your appreciation. I'm happy to hear that you've learned a lot from our interaction. If you have any more questions or need further assistance in the future, feel free to ask.

**Comment by mechano** [comment]
I also have F303 chip and my firmware works.

If you can't compile in chinese, there may be problems of charset and language direction.
So you have to understand the error, and check on Internet chinese printing issues fo compiling Marlin also for different printers i.e. Ender. 

![image](https://github.com/mechano/Kingroon_KP3S_Pro_Marlin_Firmware/assets/2874499/0fa1c2fb-aa56-4015-b08d-91fd979df81a)

**Comment by kiong2016** [comment]
Learning English is also a great endeavor. One cannot rely solely on what they are accustomed to; they should always try new things.
