### ISSUE TITLE
LED Blinking ... 

### ISSUE THREAD

**Issue by Norbas7** [mechano/Kingroon_KP3S_Pro_Marlin_Firmware#8]
I installed LED lighting. On the stock firmware, the light is OK. On Marlin, when the printer is printing, I can see that the LEDs are blinking. Is it possible to change the frequency in Marlin? Apparently this is why the LEDs blink.
PS. Do you have a photo of how you connected the 3DTouch cables to the board?
Regards

**Comment by mechano** [comment]
I don't know about led light, I don't use it.

Here where to attach the 3d Touch wires:

![image](https://github.com/mechano/Kingroon_KP3S_Pro_Marlin_Firmware/assets/2874499/9c3a7732-dca3-48fa-8ca3-afac9f62b048)
